baseURL: https://dev.nategramer.com
languageCode: en-us
title: Nate Gramer
theme: PaperMod

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nate Gramer
  description: "A personal website. Tech stuff, personal projects, photography"
  keywords: [Personal Website, Blog, Portfolios, Bio]
  author: Nate
  # author: ["Me", "You"] # multiple authors
  images: []
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  hideFooter: true
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Nate Gramer"
    icon: ""
    iconHeight: 25

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    subtitle:
    imageUrl: "images/Nate-Gramer.jpg"
    imageWidth: 240
    imageHeight: 240
    imageTitle: My face
    buttons:
      - name: Work
        url: work-bio
      - name: Life
        url: life

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: This N8

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/nathan-g-6a6546a8/"
    - name: github
      url: "https://github.com/n8tg"
    - name: email
      url: "mailto:nate@nategramer.com"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    image: "images/bob-me.png"

  editPost:
    URL: "https://github.com/n8tg/Personal-Website"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Work
      name: Work
      url: /work-bio/
      weight: 10
    - identifier: Life
      name: Life
      url: /life/
      weight: 20
    - identifier: Photography
      name: Photography
      url: https://www.nateg.photos
      weight: 30
    - identifier: Posts
      name: Posts
      url: /categories/

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai