name: "[CI] Deploy Main Site"

# This will always keep the development site up to date for hotfixes.
on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    name: Build site and save as an artifact
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build
      working-directory: nategramer.com
      run: hugo --minify

    - name: Save built site as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Built-Site
        path: nategramer.com/public

  deploy-site:
    runs-on: ubuntu-latest
    name: Copy site artifact to S3 and invalidate CloudFront distribution
    needs: ["deploy-environment", "build-site"]
    steps:
    - name: Retrieve Site artifact
      uses: actions/download-artifact@v2
      with:
        name: Built-Site

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync . s3://nategramer --delete

    - name: Get CloudFront Distribution Details
      run: |
        echo "CF_DEPLOYMENT=$(aws cloudformation describe-stack-resource \
        --stack-name nategramer \
        --logical-resource-id cloudfrontDistribution \
        | jq -r .StackResourceDetail.PhysicalResourceId)" >> $GITHUB_ENV
    
    - name: Invalidate Cloudfront distribution
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ env.CF_DEPLOYMENT }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-environment:
    runs-on: ubuntu-latest
    name: Deploy CloudFormation Template
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
   
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: nategramer
        template: MasterAWSEnvironment.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: "SSLCertARN=${{ secrets.AWS_SSL_CERT_ARN }}"
