name: Destroy Development Environment

on:
  delete:
    branches:
    - "*"
    - "!master"

jobs:
  clean-env:
    runs-on: ubuntu-latest
    name: Remove branch deployed environment 
    steps:
    - name: Save branch name in ENV
      run: | 
        echo ::set-env name=branch::${GITHUB_REF#refs/*/}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Empty S3 bucket with the AWS CLI
      run: |
        aws s3 rm s3://${{ env.branch }}.nategramer --recursive

    - name: Remove CloudFormation Stack with AWS CLI
      run: |
        aws cloudformation delete-stack --stack-name ${{ env.branch }}-nategramer